# Default values for helmchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
    #Ask about repository setting
    repository: 
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ''
    containerPort: 8081

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

service:
    type: ClusterIP
    port: 8081
    targetPort: 8081

envConfigFile: "env-config.js"

envVariables:
    reactAPIPlatform: "test"
    kaiRestAPIHost: "http://api.host/"
    cognitoUserpoolID: "us-east-1_ABC1def2g"
    cognitoClientID: "apples"