# Default values for helmchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
    #Ask about repository setting
    # repository: image-registry.openshift-image-registry.svc:5000/kai-ui-docker-5/kai:latest
    # macenturalxl1/kai-ui-image:v4
    repository: a-docker-repo/kai-image
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ''
    containerPort: 8081

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

service:
    type: ClusterIP
    port: 8081
    targetPort: 8081

envConfigFile: "env-config.js"

envVariables:
    reactAPIPlatform: "test"
    kaiRestAPIHost: "http://openshift.host.co.uk/"
    cognitoUserpoolID: "us-east-1_ABC1def2g"
    cognitoClientID: "c0gN1t0Id"