FROM node:13.12.0-alpine
# Specify app directory in the image
WORKDIR /app
# Node modules
ENV PATH /app/node_modules/.bin:$PATH
# Copy package and package-lock jsons over to app in the image
COPY ./package*.json ./app
# Copy all code to app in the image
COPY . ./app
# Install dependencies
RUN npm install --silent
# Run app in development mode
CMD ["npm", "start"] 