apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "helmchart.fullname" . }}
data:
    web.properties: |
        window.REACT_APP_API_PLATFORM= "AWS"
        window.REACT_APP_KAI_REST_API_HOST= "https://MY_API_LOCATION.execute-api.us-east-1.amazonaws.com/prod"
        window.REACT_APP_COGNITO_USERPOOLID= "us-east-1_ABC1def2g"
        window.REACT_APP_COGNITO_CLIENTID= "apples"
