apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "helmchart.fullname" . }}
data:
    web.properties: |
        window.REACT_APP_API_PLATFORM= "{{.Values.envVariables.reactAPIPlatform}}"
        window.REACT_APP_KAI_REST_API_HOST= "{{.Values.envVariables.kaiRestAPIHost}}"
        window.REACT_APP_COGNITO_USERPOOLID= "{{.Values.envVariables.cognitoUserpoolID}}"
        window.REACT_APP_COGNITO_CLIENTID= "{{.Values.envVariables.cognitoClientID}}"
        window.REACT_APP_AUTH_ENDPOINT="{{.Values.envVariables.kaiRestAPIHost}}"
