apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmchart.fullname" . }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helmchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helmchart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          - name: REACT_APP_API_PLATFORM
            value: WefwfWF
          - name: REACT_APP_KAI_REST_API_HOST
            value: nbdqlbejq
          - name: REACT_APP_COGNITO_USERPOOLID
            value: wfewF
          - name: REACT_APP_COGNITO_CLIENTID
            value: WEF
          - name: SKIP_PREFLIGHT_CHECK
            value: "true"
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: env-js-config
              subPath: {{ .Values.envConfigFile }}
      volumes:
        - name: env-js-config
          configMap:
            name: {{ include "helmchart.fullname" . }}
            items:
            - key: "web.properties"
              path: {{ .Values.envConfigFile }}
